### ISSUE TITLE
Request: Move to an existing window

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#80] opened 2014-11-17 06:05 UTC
I would like to request to move the right click option to move to an existing windows and then the drop down menu should show the different windows and maybe an option to select if when you do that put them at the end or at the start. 

Dragging and dropping the tabs works but is kinda buggy when you do it with large groups of tabs and sometimes it gets messy.

Also would be nice to have the ability perhaps to send the group of tabs to an existing bookmark folder.

**Comment by piroor** [comment] 2015-02-26 15:33
I have less motivation to implement such a feature because Firefox itself doesn't have it...
Even if it is landed to MTH, I'll never use it, so I don't want to add codes for such a feature needless for me.

However, if there is any other addon who provide a feature like "move tab to specified window", I'll make MTH compatible to it. I'm positive to make my addon collaborative with others.

**Comment by holocronweaver** [comment] 2015-07-23 22:04
I would also very much like this feature should it become possible. It seems in scope since it is a bulk tab operation, and only a small conceptual variation on the existing `Move to new window`. Having it missing makes this addon incomplete for its stated aim of bulk tab management. That said, love this addon. =)

**Comment by sambul13** [comment] 2015-11-12 16:04
piroor wrote:
"I have less motivation to implement such a feature because Firefox itself doesn't have it."

Very strange explanation. Add-ons sole purpose is to extend Firefox functionality, not to duplicate it.

In fact, "Move to Existing Window" is the ONLY feature many users look for among FF plugins and can't find. It was always available in original Opera browser (not Chrome based): just click Windows icon on the sidebar, select tabs and drag to any open window - extremely useful for presorting tabs before saving select windows to separate Sessions, all-in-one Toolbar functionality. 

I installed your plugin solely to use this feature, but... its missing. Dragging tabs by hand is a lot more cumbersome and messy, when the desktop is cluttered. This is MUST HAVE functionality.

And the other thing: users seek integration, when a single plugin covers a scope of related functions. No need to install hundreds of buggy plugins with varying UI to perform similar functions. In fact, many users are already lost among multitude of overlapping in functionality plugins they have to install just to get a single feature from each they need most.

**Comment by piroor** [comment] 2015-11-15 18:54
> Very strange explanation. Add-ons sole purpose is to extend Firefox functionality, not to duplicate it. 

Yes. But there are two levels for features of addons. 

The first level just extends Firefox's original one - for example, Firefox can reload a tab, then MTH allows to reload multiple selected tabs. Note, the basic feature is Firefox native. Such new "do something for selected tabs" features are easy to be implemented because I can reuse Firefox's internal functions.

The second level feature adds new features. For example, Firefox doesn't provide ability to copy the title of tabs but MTH provides a command to do it for selected tabs. Such a feature is hard to be introduced because I have to do it from scratch. Currently MTH has only a few of such features because I really require them - I'm the prime user of this addon. However, these features can be debts in the future by Firefox's spec changes. I only have motivation to maintain existing features in the future, in other words, features never used by me won't be maintained by me in the future. Instead, I just add some menus to call functions of other addons like "lock tabs" based on Tab Mix Plus's one. I think this is a realistic way. If there are another addon to add a "move tab to another window" menu for tabs, I'll add "move selected tabs to another window" command for users of the addon.

**Comment by sambul13** [comment] 2015-11-19 22:42
> If there are another addon to add a "move tab to another window" menu for tabs, I'll add "move
> selected tabs to another window" command for users of the add-on.

Windows Master is the only Firefox add-on I found capable of moving selected tabs between open FF windows on the same, or between different PC monitors. Unfortunately, it can only move ONE tab at a time to a chosen window. Can you add to it the ability to move several selected tabs at once to another FF window?

**Comment by rayman89** [comment] 2015-11-20 00:52
@piroor 
What about this? Tab utilities fixed and tab mix plus add the functionality to fuse x window with an other existing window and you can select which one. Using that could you make the drop down menu we requested and make your add-on move the selected tabs to a new window and then fuse that new window with the selected window from the dropdown menu all in one go?

**Comment by piroor** [comment] 2015-11-27 18:33
@sambul13 Thanks, it's interesting addon! Hmm, however it is very hard that MTH calls its feature. Instead, it seems easy that Window Master calls MTH's APIs.

**Comment by piroor** [comment] 2015-11-27 18:57
@rayman89 Thanks. Tab Utilities Fixed https://addons.mozilla.org/ja/firefox/addon/tab-utilities-fixed/ has a menu to do it. a9fc6df copies its menu to MTH's selection menu and I've confirmed it works.

**Comment by piroor** [comment] 2015-11-27 19:01
@rayman89 I couldn't find out the feature from Tab Mix Plus. Could you describe how to activate it?

**Comment by rayman89** [comment] 2015-11-27 23:32
@piroor I cheked again and I was wrong TMP has the fuse option but it does not let you choose.

**Comment by gene-pavlovsky** [comment] 2016-07-02 17:24
To get this behavior, I use Multiple Tab to select a bunch of tabs, then copy their URIs to the clipboard.
Then I open a new window (or tab group) and use the Copy URLs Expert to create new tabs from clipboard. Not perfect but works.

**Closed** 2018-08-28 12:58 UTC
Labels: out of purpose
