### ISSUE TITLE
Keyboard Shortcuts: Particularly Close Selected Tabs

### ISSUE THREAD

**Issue by roseuz** [piroor/multipletab#65] opened 2014-02-22 22:51 UTC
I would love it if there were keyboard shortcuts implemented for the right click context menu options. In particular, I would like for there to be a shortcut for closing selected tabs. After I bookmark selected tabs, I would then like to close them with a keyboard shortcut.

**Comment by piroor** [comment] 2015-02-26 19:03
Firefox already has too many keyboard shortcuts so it is very difficult to assign new clean shortcut for my addon. Then a keyboard shortcut customizing feature will be needed - but I think it is not MTH's job. Instead MTH provides public APIs for other addons, so custom keyboard shortcuts can be done by other addons for the purpose.

**Comment by s101d1** [comment] 2017-01-20 21:25
I also need keyboard shortcut for closing selected tabs, preferably using default close tab shortcut (Ctrl+W). Is it possible for you to add this feature? I don't really need full fledged keyboard shorcut binding for eveything, I just need to be able to close selected tabs with a shortcut. And I don't really like the idea of installing another add-on for this, but if you can't make it, then what are the suggested addons that able to customize the shortcut?

**Comment by pieqq** [comment] 2017-12-13 08:30
I would also love a keyboard shortcut to close selected tabs. The best would be to map Ctrl+W to "Close all selected tabs" if at least one tab is selected.

My current setup:

- Firefox 57
- Tree Style Tab
- Multiple Tabs

My problem:

Since Tree Style Tab is installed, I have to

1. select the tabs in it, 
2. right click,
3. select `Selected Tabs`
4. select `Close Tabs`

The problem is the first submenu has two submenus (`Tree Style Tabs >` and `Selected Tabs >`) and usually my cursor ends up hovering one of these, which in return shows the content of the submenu immediately. It's very annoying because then it's very cumbersome to get rid off that submenu, or to actually get to select `Close Tabs`.

Here is how it looks when I right click on a group of tabs (step 2):

![Screenshot of context menu](https://i.imgur.com/ZFADDwr.png)

The only workaround I found so far is just to uncheck all the options in TST's `Additional Context Menu Items` and in MTH's `Extra Context Menu Items` (apart from `Close Tabs`), because it then makes the TST's submenu disappear entirely which allows me to easily select `MTH > Close Tabs`.

**Comment by piroor** [comment] 2020-03-05 16:28
Now Firefox natively has this feature.

**Closed by piroor** 2020-03-05 16:28 UTC
Labels: out of purpose
